### PR TITLE
Add My Submissions page

### LINKED ISSUE #77: /my-submissions page
Since we are not sending any notifications.... we need a page so people can check their submissions

### PR DESCRIPTION
**Pull request by damianmarti**
Added My Submissions item to the header (only shown when the user connects the wallet).

No submissions:

localhost_3000_my-submissions (1)

With submissions:

localhost_3000_my-submissions

closes #77

### CODE REVIEW

**Review by Pabl0cks — APPROVED** [review]
Thanks for tackling it so fast @damianmarti !! I've pushed some small tweaks to:

- Add some padding for small devices, tried to set same paddings as /submissions
- "My Submissions" was jumping to 2 lines in some screen sizes + hamburger

I was having problems when trying to access /my-submissions in a new tab, or reloading /my-submissions when it was already loaded. It was redirecting me to homepage. 

Tried to add a quick fix, but started fixing some other small issues I found (double notification when no connected account, flickering before showing your submissions, flickering when disconnecting after loading the submissions) so I probably ended up pushing some really dumb code. 

So I'd love if you could review https://github.com/BuidlGuidl/extensions-hackathon/pull/83/commits/46913d954711a4441bdccfcb9c572102b4ab5dcb (feel free to undo and fix it properly if it's too messy)

**Comment by damianmarti** [comment]
> Thanks for tackling it so fast @damianmarti !! I've pushed some small tweaks to:
> 
> * Add some padding for small devices, tried to set same paddings as /submissions
> * "My Submissions" was jumping to 2 lines in some screen sizes + hamburger
> 
> I was having problems when trying to access /my-submissions in a new tab, or reloading /my-submissions when it was already loaded. It was redirecting me to homepage.
> 
> Tried to add a quick fix, but started fixing some other small issues I found (double notification when no connected account, flickering before showing your submissions, flickering when disconnecting after loading the submissions) so I probably ended up pushing some really dumb code.
> 
> So I'd love if you could review [46913d9](https://github.com/BuidlGuidl/extensions-hackathon/commit/46913d954711a4441bdccfcb9c572102b4ab5dcb) (feel free to undo and fix it properly if it's too messy)

Thanks @Pabl0cks !!

I took a different approach (I think it's simpler) showing a connect button instead of redirecting the user to the home. 

Please, take a look at https://github.com/BuidlGuidl/extensions-hackathon/pull/83/commits/dd1041ce77a7a7ed5e7f0b69ed671758d1c5a844 and let me know what you think.

**Comment by Pabl0cks** [comment]
> I took a different approach (I think it's simpler) showing a connect button instead of redirecting the user to the home.

I think this approach makes much more sense! 🙌 Even the /my-submissions header link could be always shown with this approach.

Did some testing, found some issues, mostly flickerings:

- When I go to /my-submissions manually, I get infinite loading (not normal use case but if it's easy I'd handle it, specially if we decide to show /my-submissions when disconnected)
- When I connect with a wallet with submissions, I go to /my-submissions and it shows the "No submissions msg"+ submit button for a couple of seconds on the first access. If I reload, I get the "Connect" button for a second, then "No submissions" for another second, then the submissions load normally.
- When I disconnect having the /my-submissions opened, I get some flickering with the Loading... and "Connect Wallet msg + button"

Suggestion: Maybe we could check if the submissions are open to show the "Submit an Extension" button normally, or show "Submissions closed" and disabled otherwise, like we do in /submit

**Comment by damianmarti** [comment]
> > I took a different approach (I think it's simpler) showing a connect button instead of redirecting the user to the home.
> 
> I think this approach makes much more sense! 🙌 Even the /my-submissions header link could be always shown with this approach.
> 
> Did some testing, found some issues, mostly flickerings:
> 
> * When I go to /my-submissions manually, I get infinite loading (not normal use case but if it's easy I'd handle it, specially if we decide to show /my-submissions when disconnected)
> * When I connect with a wallet with submissions, I go to /my-submissions and it shows the "No submissions msg"+ submit button for a couple of seconds on the first access. If I reload, I get the "Connect" button for a second, then "No submissions" for another second, then the submissions load normally.
> * When I disconnect having the /my-submissions opened, I get some flickering with the Loading... and "Connect Wallet msg + button"
> 
> Suggestion: Maybe we could check if the submissions are open to show the "Submit an Extension" button normally, or show "Submissions closed" and disabled otherwise, like we do in /submit

@Pabl0cks thanks for the testing!

I added the submissionsEnabled check and I refactored to use useQuery. 

It works much better now!

**Comment by Pabl0cks** [comment]
> I added the submissionsEnabled check and I refactored to use useQuery.
> 
> It works much better now!

TYSM Damu! useQuery is handling the flickering muuch better ♥. 

The only use case that has some flickering is disconnect while you are in /my-submissions, either with a user with submissions or  without submissions.

If it's a PITA to fix, we could merge and document the flickering in issues. Not like it's going to be a very common use case (maybe some user that connected with the wrong address?)

**Comment by damianmarti** [comment]
> > I added the submissionsEnabled check and I refactored to use useQuery.
> > It works much better now!
> 
> TYSM Damu! useQuery is handling the flickering muuch better ♥.
> 
> The only use case that has some flickering is disconnect while you are in /my-submissions, either with a user with submissions or without submissions.
> 
> If it's a PITA to fix, we could merge and document the flickering in issues. Not like it's going to be a very common use case (maybe some user that connected with the wrong address?)

Thanks!!

Yeah, there are some flickering issues when disconnecting, but I checked, and it's not so easy to fix. I think this can be left as a known bug for now.

**Comment by Pabl0cks** [comment]
> Yeah, there are some flickering issues when disconnecting, but I checked, and it's not so easy to fix. I think this can be left as a known bug for now.

Ok! Merging

**Pull request merged**
