### PR TITLE
refactor: Add tabs to admin for votes

### PR DESCRIPTION
**Pull request by ChangoMan**
## Description

Adding some tabs to switch between viewing submissions with votes and without votes. We could also add another tab for `all` if we want.

### Screenshots

Screenshot 2024-08-25 at 12 57 39 PM

### CODE REVIEW

**Comment by carletex** [comment]
Not sure what is more valuable (and I guess it depends on what we are looking for)

1. This PR (votes vs no votes)
2. Having "pending" / "already voted" for the **current admin**. So you know which ones are waiting for_your_ votes.

Thoughts? 

Also cc @damianmarti @Pabl0cks @technophile-04

**Comment by damianmarti** [comment]
> Not sure what is more valuable (and I guess it depends on what we are looking for)
> 
> 1. This PR (votes vs no votes)
> 2. Having "pending" / "already voted" for the **current admin**. So you know which ones are waiting for_your_ votes.
> 
> Thoughts?
> 
> Also cc @damianmarti @Pabl0cks @technophile-04

Yes, we need to know what submissions the current admin is pending for voting. 

It could be this same PR, but changing how the votes/no votes arrays are populated...

**Comment by ChangoMan** [comment]
> Not sure what is more valuable (and I guess it depends on what we are looking for)
> 
> 1. This PR (votes vs no votes)
> 2. Having "pending" / "already voted" for the **current admin**. So you know which ones are waiting for_your_ votes.
> 
> Thoughts?
> 
> Also cc @damianmarti @Pabl0cks @technophile-04

Got it, sounds like option 2 would be more valuable. I've adjusted the code to be `voted` and `notVoted` based on the currently connected admin

**Review by technophile-04 — APPROVED** [review]
Yup agree that option 2 would be helpful and make more sense!! I see Hunter already updated it 🙌

**Comment by carletex** [comment]
Great, yeah! Definitely, 2 makes more sense if we want all the admins to vote for every submission (if we make this a hackathon 
 started kit, we could implement "assignments" in case there are a lot of submissions).

It's working great, Hunter! A few things that we could improve (open to discussion, and no need to tackled on this PR!)

1. Could we add the number next to each title (e.g. Not voted (5) / Voted (18))?
2. Let's add a message (in dark grey maybe?) saying that there are no submissions (in the given tab)
image
3. The tabs have different positions on empty sections and non-empty sections. Compare the previous screenshot with (centered vs left aligned):
image
4. Maybe we should have a loading state until we have the `address` of the admin? If not, the voted ones load in "Not voted" and they disappear in your face when `address` is available.

Let me know what you think!

**Comment by ChangoMan** [comment]
> Great, yeah! Definitely, 2 makes more sense if we want all the admins to vote for every submission (if we make this a hackathon started kit, we could implement "assignments" in case there are a lot of submissions).
> 
> It's working great, Hunter! A few things that we could improve (open to discussion, and no need to tackled on this PR!)
> 
> 1. Could we add the number next to each title (e.g. Not voted (5) / Voted (18))?
> 2. Let's add a message (in dark grey maybe?) saying that there are no submissions (in the given tab)
> 3. The tabs have different positions on empty sections and non-empty sections. Compare the previous screenshot with (centered vs left aligned):
> 4. Maybe we should have a loading state until we have the `address` of the admin? If not, the voted ones load in "Not voted" and they disappear in your face when `address` is available.
> 
> Let me know what you think!

I can get 1 and 2 in a new PR. I've fixed 3 and 4 in this current PR

**Review by carletex — APPROVED** [review]
Thanks @ChangoMan looking great!!

Pushed some silly optimizations: https://github.com/BuidlGuidl/extensions-hackathon/pull/65/commits/ed1bcacafdfe4819bc396b6e3a40691b05462f44

**Pull request merged**
